contaobackup:
    path: /contaobackup
    defaults:
        _controller: BohnMedia\ContaoBackupBundle\Controller\BackupController:loadAction
        _scope: frontend
        _token_check: false

defaultbackuppassword:
    path: /defaultbackuppassword
    defaults:
        _controller: BohnMedia\ContaoBackupBundle\ContaoBackup:generateDefaultPasswordRequest
        _scope: frontend
        _token_check: false