contaobackupdumpdb:
  path: /contaobackup/dumpdb
  defaults:
    _controller: BohnMedia\ContaoBackupBundle\Controller\BackupController:dumpdb
    _scope: frontend
    _token_check: false

contaobackuplist:
  path: /contaobackup/list
  defaults:
    _controller: BohnMedia\ContaoBackupBundle\Controller\BackupController:list
    _scope: frontend
    _token_check: false

contaobackupfile:
  path: /contaobackup/file
  defaults:
    _controller: BohnMedia\ContaoBackupBundle\Controller\BackupController:file
    _scope: frontend
    _token_check: false

defaultbackuppassword:
  path: /defaultbackuppassword
  defaults:
    _controller: BohnMedia\ContaoBackupBundle\Controller\BackupController:generateDefaultPassword
    _scope: frontend
    _token_check: false
