contaobackup:
    path: /contao/backup
    defaults:
        _controller: BohnMedia\ContaoBackupBundle\Controller\BackupController:loadAction
        _scope: frontend
        _token_check: false
    requirements: -