services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    bohnmedia.contaobackup:
        class: BohnMedia\ContaoBackupBundle\ContaoBackup
        arguments:
            - '%kernel.project_dir%'

    BohnMedia\ContaoBackupBundle\Controller\BackupController:
        arguments:
            - "@contao.framework"
            - '@bohnmedia.contaobackup'
        tags: ['controller.service_arguments']