services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    BohnMedia\Controller\BackupController:
        arguments:
            - '%kernel.project_dir%'
            - "@session"
            - "@contao.framework"
        tags: ['controller.service_arguments']